name: Deploy
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      cron_action:
        description: "Enable or disable cron job"
        required: true
        default: "enable"
        options:
          - enable
          - disable

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Set Environment Variable for Cron Job
        if: ${{ github.event.inputs.cron_action == 'enable' || github.event.inputs.cron_action == 'disable' }}
        run: |
          if [ "${{ github.event.inputs.cron_action }}" == "enable" ]; then
            deno deploy --project "katayama800-push-notifi-92" --env CRON_ENABLED=true
          else
            deno deploy --project "katayama800-push-notifi-92" --env CRON_ENABLED=false
          fi
        shell: bash

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "katayama800-push-notifi-92"
          entrypoint: "main.ts"
          root: "src/"
